-- CR7 database migration; version 20260909163000; view definition revision.
CREATE OR REPLACE VIEW BB_POC_RELEASE_FLOW_V AS
SELECT ID, NAME, STATUS, CREATED_AT,
       CASE WHEN STATUS = 'ACTIVE' THEN 1 ELSE 0 END AS IS_ACTIVE
FROM BB_POC_RELEASE_FLOW;
