-- CR7 All Goals POC migration V1.0.0.0.
-- One logical DDL change: create the release-flow table with required metadata.
CREATE TABLE BB_POC_V1_RELEASE_FLOW (
    RELEASE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    RELEASE_NAME VARCHAR2(200) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BB_POC_V1_RELEASE_FLOW PRIMARY KEY (RELEASE_ID)
);

COMMENT ON TABLE BB_POC_V1_RELEASE_FLOW IS
    'POC release-flow records managed through Bytebase migrations (mutation test).';
COMMENT ON COLUMN BB_POC_V1_RELEASE_FLOW.RELEASE_ID IS
    'Surrogate identifier for the release-flow record.';
COMMENT ON COLUMN BB_POC_V1_RELEASE_FLOW.RELEASE_NAME IS
    'Human-readable name of the release flow.';
COMMENT ON COLUMN BB_POC_V1_RELEASE_FLOW.CREATED_AT IS
    'Timestamp at which the release-flow record was created.';
