-- CR7 All Goals POC migration V1.0.0.7.
-- Valid migration used to verify that a later file remains pending when V1.0.0.6 fails.
CREATE TABLE "bb_poc_v1_retry_probe" (
    "retry_id" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "retry_code" VARCHAR2(50) DEFAULT 'PENDING' NOT NULL,
    "created_at" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT "bb_poc_v1_retry_probe_pk" PRIMARY KEY ("retry_id")
);

COMMENT ON TABLE "bb_poc_v1_retry_probe" IS
    'POC table for verifying retry behavior after a failed migration.';

COMMENT ON COLUMN "bb_poc_v1_retry_probe"."retry_id" IS
    'Generated identifier for the retry probe record.';

COMMENT ON COLUMN "bb_poc_v1_retry_probe"."retry_code" IS
    'Status code used by the rollout retry test.';

COMMENT ON COLUMN "bb_poc_v1_retry_probe"."created_at" IS
    'Timestamp when the retry probe record is created.';
