-- CR7 All Goals POC migration V1.0.0.9.
-- Valid migration that should remain pending when V1.0.0.8 fails.
CREATE TABLE "bb_poc_v1_after_failure" (
    "record_id" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "record_status" VARCHAR2(20) DEFAULT 'READY' NOT NULL,
    "created_at" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT "bb_poc_v1_after_failure_pk" PRIMARY KEY ("record_id")
);

COMMENT ON TABLE "bb_poc_v1_after_failure" IS
    'POC table used to verify that later migrations wait for a failed task.';

COMMENT ON COLUMN "bb_poc_v1_after_failure"."record_id" IS
    'Generated identifier for the post-failure rollout test.';

COMMENT ON COLUMN "bb_poc_v1_after_failure"."record_status" IS
    'Initial status for the post-failure rollout test.';

COMMENT ON COLUMN "bb_poc_v1_after_failure"."created_at" IS
    'Timestamp when the post-failure test record is created.';
