-- CR7 All Goals POC migration V1.0.0.8.
-- Fixed migration after the intentional ORA-00942 rollout failure.
CREATE TABLE "bb_poc_v1_missing_runtime_target" (
    "failure_id" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "failure_marker" VARCHAR2(30) DEFAULT 'RECOVERED' NOT NULL,
    "created_at" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT "bb_poc_v1_missing_runtime_target_pk" PRIMARY KEY ("failure_id")
);

COMMENT ON TABLE "bb_poc_v1_missing_runtime_target" IS
    'POC table created by the corrected migration after a runtime failure.';

COMMENT ON COLUMN "bb_poc_v1_missing_runtime_target"."failure_id" IS
    'Generated identifier for the corrected runtime-failure test.';

COMMENT ON COLUMN "bb_poc_v1_missing_runtime_target"."failure_marker" IS
    'Marker showing that the corrected migration was applied.';

COMMENT ON COLUMN "bb_poc_v1_missing_runtime_target"."created_at" IS
    'Timestamp when the corrected runtime-failure test row is created.';
